### PR TITLE
New stickers 2024-06-24

### PR DESCRIPTION
**Pull request by levimcg**
Hey, @basham this is the first time adding new stickers to the library. It seems pretty straightforward. Everything looks good in the local repo. Would you be able to take a quick look at this. No big deal if not.

### CODE REVIEW

**Review by basham — APPROVED** [review]
I pulled the branch and tested it. The file names and file contents looks good. The color and size APIs work on them. Looks great!

**Comment by levimcg** [comment]
Woohoo! thanks for the quick response. I'm going go ahead and push out a new release (`0.3.0`)

**Comment by basham** [comment]
I think the name `flag-america` is fine. The alternative I'd consider is `flag-usa`, as it is shorter and has the full country name.

**Comment by levimcg** [comment]
Oooh, that's a good call. I'll make that update

**Comment by levimcg** [comment]
Updated `flag-america` to `flag-usa`. I'm going to merge this and get a new 0.3.0 release out.

**Pull request merged**
